### ISSUE TITLE
hr status bar

### ISSUE THREAD

**Issue by peckto** [Fraunhofer-AISEC/penlog#29]
When logging with penlog, you often want to see progress of your program and on the other side, you do not want to have to much spam on your screen, hiding the important messages.
It would be nice, to have something like a progress bar in `hr`.
As progress output, we could use the `info` log level.
The progress bar could be implemented as CR.
Meaning, we could print the `info` log level in the same line with `CR` without `LF`.
All other log level could be printed regular with `LF`.

This option may be only useful when doing live logging and is not helpeful when reading from file.

**Comment by mrgreenhub** [comment]
Implemented in a a very simple fashion in #30.
@rumpelsepp While at first sight this might better fit into the formatter, the problem there is that you don't handle newlines in the formatter but via a simple fmt.Println in the converter, so it needs to go there. Do you agree?.

**Comment by rumpelsepp** [comment]
Is implemented.
